# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "fivexl-terraform-backend"
    encrypt = true
    key     = "dev/vpc/terraform.tfstate"
    region  = "eu-west-1"
  }
}
